[project]
name = "predicting-road-accident-risk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numba==0.60.0",
    "shap>=0.49.1",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
